### ISSUE TITLE
upload_forecast() return error while uploading: Error in httr::upload_file(temp_json_file) : file.exists(path) is not TRUE

### ISSUE THREAD

**Issue by kgle1921** [reichlab/zoltr#19]
[zoltR_upload_test.zip](https://github.com/reichlab/zoltr/files/3946627/zoltR_upload_test.zip)
Steps to reproduce the errors:

1. Download the attach zip file (zoltr_upload.R and EW43-2019-FluOutlook_Mech.csv inside): The csv file is a sample forecast from this season, and the test script is used to upload this file to Khoa_test_project on zoltar
2. Need to have zoltR, install the developer version on github: devtools::install_github("reichlab/zoltr", force = TRUE)
3. Run the zoltr_upload.R using Rstudio

Expected output: The upload_forecast() function returns an upload_file_job_id to track the status of the upload

Actual output:
upload_forecast(): POST: https://zoltardata.com/api/model/144/forecasts/
Error in httr::upload_file(temp_json_file) : 
  file.exists(path) is not TRUE

**Comment by matthewcornell** [comment]
fixed original error, but upload file jobs fail:
```
FAILED_PROCESS_FILE: exc=unhashable type: 'list', traceback=Traceback (most recent call last): File "/app/forecast_app/models/upload_file_job.py", line 157, in upload_file_job_cloud_file yield upload_file_job, cloud_file_fp File "/app/forecast_app/views.py", line 1116, in process_upload_file_job__forecast load_predictions_from_json_io_dict(new_forecast, json_io_dict) File "/app/.heroku/python/lib/python3.6/contextlib.py", line 52, in inner return func(*args, **kwds) File "/app/utils/forecast.py", line 239, in load_predictions_from_json_io_dict _prediction_dicts_to_validated_db_rows(forecast, prediction_dicts) File "/app/utils/forecast.py", line 270, in _prediction_dicts_to_validated_db_rows if location_name not in location_name_to_obj: TypeError: unhashable type: 'list' 
```

**Comment by matthewcornell** [comment]
Closing this b/c it's fixed, but this exposed another problem. Also, zoltar2 is changing in the next weeks
