### ISSUE TITLE
can't get project data (without authentication?)

### ISSUE THREAD

**Issue by nickreich** [reichlab/zoltr#23]
I didn't authenticate, but should still be able to get public info/data

```
> zoltar_connection <- new_connection()
> the_projects <- projects(zoltar_connection)
get_resource(): GET: https://zoltardata.com/api/projects/
Error in get_resource(zoltar_connection, url_for_projects(zoltar_connection)) : 
  Forbidden (HTTP 403).
```

**Comment by nickreich** [comment]
I guess now I am remembering that we did this to avoid bots hitting it...

**Comment by matthewcornell** [comment]
Yes, we decided that any API access requires an account. The docs say this too. Are you rethinking this?

**Comment by nickreich** [comment]
Is there some middle ground, to allow people to download public data without having the API be overloaded by bots?

**Comment by matthewcornell** [comment]
Maybe we are talking about two different things:
1. _Authorization_ (who can view what). currently you must at least be _authenticated_ (i.e., have an account)
2. _Bandwidth_ (how much users are allowed).

The API library we use does seem to have support for _throttling_: https://www.django-rest-framework.org/api-guide/throttling/ . I've never dealt with this before.

**Comment by mzorn-58** [comment]
Can this issue be closed?

**Comment by matthewcornell** [comment]
We'd need to work out the above issues before moving forward. Prioritization is up to @nickreich .

**Comment by nickreich** [comment]
I don't think there's a clear issue here. going to close it.
