### ISSUE TITLE
provide more detailed instructions about .Renviron file

### ISSUE THREAD

**Issue by nickreich** [reichlab/zoltr#24]
we have this right now on this page http://reichlab.io/zoltr/articles/getting-started.html:

> For this and other vignettes, you will need to create an .Renviron file that contains Z_USERNAME and Z_PASSWORD variables that match your account settings (note the Z_ prefix).

Can we be really explicit about where .Renviron should live (in your root directory? is it platform specific?) and exactly what lines should be added?

**Comment by matthewcornell** [comment]
This wasn't enough?

![Screen Shot 2020-05-09 at 9 50 58 AM](https://user-images.githubusercontent.com/1034007/81475494-9e1fbe80-91da-11ea-8782-a9c013f83da6.png)

**Comment by nickreich** [comment]
where is this? I was looking here: http://reichlab.io/zoltr/articles/getting-started.html#connect-to-the-host-and-authenticate

**Comment by nickreich** [comment]
I think just something that says that .Renviron needs to be in your home directory and needs to have the following two lines in it:
```
Z_USERNAME = insert-your-username-here
Z_PASSWORD = insert-your-password-here
```

**Comment by matthewcornell** [comment]
First bullet:

```
Be careful to store and use your username and password so that they’re not accessible to others. A good practice is to put them them in your .Renviron file and then use Sys.getenv() to retrieve them, as outlined in Use Environment variables and as done below.
```

**Comment by nickreich** [comment]
In the getting started file I link to above, I think we need to say something like:
```
You need to have an account on Zoltar and be authenticated to the server in order to access data from the API. Once you have an account, we recommend storing your Zoltar username and password in you .Renviron file. In practice, this means having a file named .Renviron in your home directory. The lines of code below will work if you have the following two lines somewhere in your .Renviron file (where you replace your username and password in the appropriate locations):
Z_USERNAME = insert-your-username-here
Z_PASSWORD = insert-your-password-here
```

**Comment by matthewcornell** [comment]
Thanks for the prose @nickreich . I added it to the latest commit.
