### ISSUE TITLE
change example code for connecting to the host

### ISSUE THREAD

**Issue by nickreich** [reichlab/zoltr#3]
Current connection to host code displayed in the vignette is different from the code that a user needs to run. I suggest making a new chunk of R code that is not evaluated or run that displays the code a user should run and its output, i.e. 
```
conn <- new_connection()
z_authenticate(conn, Sys.getenv("USERNAME"), Sys.getenv("PASSWORD"))
conn
#> ZoltarConnection 'zoltardata.com' (authenticated)
```
and then having the existing chunk of code in the vignette actually be the code that is run, but have it be not displayed in the vignette. It would be a bit of a "lie" to the end user, but I think would achieve the same end result without having to explain why the code in the vignette is different from what they need to run.

**Comment by matthewcornell** [comment]
IIUC, this had been addressed via the `{r, include=FALSE}` and `{r, eval=FALSE}` headings.
