### ISSUE TITLE
add ability to add/edit timezeroes in a project

### ISSUE THREAD

**Issue by nickreich** [reichlab/zoltr#42]
Not sure what the right approach is here. Options as I see them:
1. Go whole hog and add an `edit_project()` function, similar to the existing `edit_model()` function. would allow for update of entire project config.
2. add a more limited update capability to add timezeroes. Maybe just an `add_timezero()` function that takes a connection object, a `model_url`, and the fields necessary to add the new timezero.

The second seems more user-friendly (i.e. the user doesn't have to download/edit json directly) and preferable. Not clear to me which would be more work or better long-term structure.

**Comment by matthewcornell** [comment]
I seem to recall we had a feature that would create a timezero before uploading if it didn't exist. I'll look for it...
