### ISSUE TITLE
upload_truth() function is not documented

### ISSUE THREAD

**Issue by nickreich** [reichlab/zoltr#45]
Looks like roxygen needs to be run and Rd files committed? seems like the documentation is there in the code:

https://github.com/reichlab/zoltr/blob/75d7dceb5c49b852e034ef08d9a221fd5ab000fa/R/project.R#L253

**Comment by matthewcornell** [comment]
Is this still an issue? I see the docs here: http://reichlab.io/zoltr/reference/upload_truth.html
