### ISSUE TITLE
add capacity to specify the `issued_at` date for an uploaded truth data batch

### ISSUE THREAD

**Issue by nickreich** [reichlab/zoltr#50]
Currently, when truth data is uploaded the upload time is automatically assigned as the `issued_at` field for that batch of truth data. But it would be nice if the user could specify a different datetime, if, for example, they are taking care to upload data "as of" a specific moment in time, but doing it after the fact.

**Comment by nickreich** [comment]
But note that you should not be allowed to upload a truth data with an issued-at date earlier than any existing issued-at date in the project.

**Comment by matthewcornell** [comment]
Note that the server *does* validate `issued_at` - see https://docs.zoltardata.com/forecastversions/#forecast-version-rules .
