### ISSUE TITLE
Versioning broken

### ISSUE THREAD

**Issue by sbfnk** [reichlab/zoltr#51]
`zoltr` [seems to have gone](https://github.com/reichlab/zoltr/blob/master/NEWS.md) from version `0.99` to `0.9.10`, i.e. a decrease. This [breaks](https://github.com/reichlab/covidHubUtils/actions/runs/3968785324/jobs/6802411085#step:10:534) installation of the `covidHubUtils` package.

**Comment by matthewcornell** [comment]
Sorry about that, Sebastian! From what I've read, version numbers are not supposed to be treated as fractions, but I guess R disagrees. I'll change zoltr to 1.0 and push this am.

**Comment by matthewcornell** [comment]
@sbfnk Where did you see that the version decrease caused the problem? In the output you link to, I only see this error:

> Error: Package required and available but unsuitable version: ‘zoltr’
> Imports includes 25 non-default packages.
> Importing from so many packages makes the package vulnerable to any of
> them becoming unavailable.  Move as many as possible to Suggests and
> use conditionally.
> See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
> manual.

**Comment by matthewcornell** [comment]
I just pushed a change to zoltr to implement #50 , and I bumped the version to 1.0.0. Hopefully [your recent PR](https://github.com/reichlab/covidHubUtils/pull/390) will continue to work. Please let us know. thx
